#!/bin/sh

FILEPATH=$(greadlink -f "$0")
DIR=$(dirname "$FILEPATH")

FILES=".bash .bashrc .gemrc .gitignore_global .gvimrc .tmux.conf .vimrc .vim .zshrc"



for FILE in $FILES; do
    SOURCE="$DIR/$FILE"
    TARGET="$HOME/$FILE"

    move_and_symlink_file () {
        if [ ! -h "${TARGET}" ]; then # if target not a symlink
            if [ -e "${TARGET}" ] ; then # if target exists
                echo "${FILE} exists, moving to ${FILE}.old";
                mv -f $TARGET $TARGET.old # move target;
           fi
        fi

        echo
        echo "Symlinking $SOURCE to $TARGET"
        if [ -h "${TARGET}" ]; then
            ln -fs $SOURCE $TARGET
        else
            ln -s $SOURCE $TARGET
        fi
        echo
    }

    while true; do
        read -p "Do you wish to symlink ${FILE}? " yn
        case $yn in
            [Yy]* ) move_and_symlink_file;
                    break;;
            [Nn]* ) break;;
            *)    echo "Please answer (y)es or (n)o.";;
        esac
    done
done

if [ ! -d "$HOME/.vim/bundle/vundle" ] ; then
    while true; do
        read -p "do you wish to install Vundle for Vim? " yn
        case $yn in
            [Yy]* ) git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle;
                    vim +BundleInstall +qall;
                    break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

if ! command -v zsh > /dev/null; then
    while true; do
        read -p "zsh not installed. Do you want to install zsh? " yn
        case $yn in
            [Yy]* ) sudo apt-get install zsh;
                    chsh -s /bin/zsh;
                    break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

if [ ! -d "$HOME/.oh-my-zsh" ] ; then
    while true; do
        read -p "Do you wish to install Oh-My-Zsh? " yn
        case $yn in
            [Yy]* ) git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh;
                    break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi


